######################################################################
# Automatically generated by qmake (2.01a) P j�l. 9 15:56:55 2021
######################################################################

TEMPLATE = console
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
